### PR TITLE
Cache UI positions for better performance.

### PR DESCRIPTION
**Pull request by chzhrr**
Recently, I noticed GenMapUI_DrawThingLabel_Patch is pretty expensive. As shown in the profiler, it costs 0.3ms per update on my small test save.
screenshot4
After some digging, I found some utility functions in Verse.UI, namely, UI.CurUICellSize, UI.MouseMapPosition, UI.MapToUIPosition, is called tons of times. And this number scales with the number of things on the screen.
screenshot5
I assume such a position or size will not change within a single frame. So caching it can prevent recalculating it for everything on the screen and greatly improve the performance.

Hope it helps.

### CODE REVIEW

**Comment by pardeike** [comment]
Well prepared and argumented

**Comment by pardeike** [comment]
@chzhrr, unfortunately I pushed this update out to 300.000 subscribers. The problem is that I now get flooded with "latest update broke zoom to mouse" messages.

**Comment by pardeike** [comment]
I fixed it in 2.3.1

**Comment by chzhrr** [comment]
Sorry for the confusion. It's an oversight because I just search all the references for that function. As in your fix, it should call UI.MouseMapPosition after updating the position. Otherwise, it will always result in Vector3.zero. Thanks for the quick fix~

**Pull request merged**
